### ISSUE TITLE
Request for enhanced residues

### ISSUE THREAD

**Issue by xanthe-cat** [tdulcet/Mlucas#6]
[Requested](https://www.mersenneforum.org/showthread.php?p=651562&postcount=106) by Gary Gostin.
The result block at about line 2511 of `Mlucas.c` has a long `snprintf` statement,
https://github.com/tdulcet/Mlucas/blob/ba49d68b8e62f272bf682f51f3ca77c1bb0e89fa/src/Mlucas.c#L2510-L2513
This might be better handled by adding a conditional `if (condition) {snprintf} else {snprintf}` that kicks in after the residue shift is printed, as the Mersenne exponents usually have a JSON string to submit to mersenne.org, while nothing is printed for Fermat exponents and the “paste the following” instruction just looks silly with no JSON to paste. Instead, it is customary to print an ‘enhanced’ residue devised by Selfridge and Hurwitz _circa_ 1964, consisting of (then) residues mod 2<sup>36</sup>, mod 2<sup>35</sup>–1, and mod 2<sup>36</sup>–1 (and now: the mod 2<sup>36</sup> is substituted by a hexadecimal mod 2<sup>64</sup> residue; you just read off the last 9 hex digits to recover the mod 2<sup>36</sup> residue). The –1 applied to the other moduli means for large values > 2<sup>36</sup> they function as a pseudo-checksum, since the chances of a coincidental alignment of all three values is ~ 1 in 2<sup>(64+35+36)</sup>.

```c
	snprintf_nowarn(cbuf,STR_MAX_LEN, "%s is not prime. Program: E%s. Final residue shift count = %llu.\n",PSTRING,VERSION,RES_SHIFT); 
	mlucas_fprint(cbuf,1);
	if (MODULUS_TYPE == MODULUS_TYPE_FERMAT) {snprintf_nowarn(cbuf,STR_MAX_LEN, "Selfridge-Hurwitz residues Res64,Res35m1,Res36m1 = %016llX,%11llu,%11llu.\n",Res64,Res35m1,Res36m1);}
	else {snprintf_nowarn(cbuf,STR_MAX_LEN, "If using the manual results submission form at mersenne.org, paste the following JSON-formatted results line:\n%s\n",cstr);}
	mlucas_fprint(cbuf,1);
```
**Edited to add**: In reviewing the code, we found several other places where it might be appropriate to print the “enhanced” residue with Selfridge–Hurwitz moduli. One is when the Suyama PRP-cofactor code is called, but this would require passing the values in, so we chose instead to modify the “restart” printout at [line 1670](https://github.com/tdulcet/Mlucas/blob/e63bdf1bf49d58a754bc80a80a4db05bcb725180/src/Mlucas.c#L1670) that precedes calling the cofactor code.

**Comment by tdulcet** [comment]
Please feel free to make a PR with this improvement or we could instead include it in a larger PR with the rest of your bug fixes. Note that Prime95/MPrime generates a Res2048 (the residue mod 2<sup>2048</sup>–1), which might be helpful to output here for Gary's website, but would require more extensive changes to generate in Mlucas.

If it would be useful, I could update my [GIMPS status](https://gist.github.com/tdulcet/19b89559f6b4f2cc2434547cc7528379) script to output the "Selfridge-Hurwitz residues" as well (it of course already outputs Res64). This would be trivial to do, since all three values are stored directly in the Mlucas savefiles.

**Comment by xanthe-cat** [comment]
I think I might try the larger PR, incorporating the various changes discussed in the forum thread, since after careful review I think most of the bug fixes can be made to behave neutrally with respect to the Mersenne exponents. The main one I’m concerned about is the change to save final PRP residues, as Mersenne cofactor testing is almost identical to the case for the Fermats, but in my testing that did not involve any problem carrying it out in the first place to successful completion, or in rerunning the test to add a factor. Now that I’ve been invited to contribute here (thank you very much) I imagine this means I may generate the pull request from this repository, rather than editing `Mlucas.c` in the fork at xanthe-cat\Mlucas?

**Comment by tdulcet** [comment]
> Now that I’ve been invited to contribute here (thank you very much) I imagine this means I may generate the pull request from this repository, rather than editing `Mlucas.c` in the fork at xanthe-cat/Mlucas?

No problem, thanks for all your contributions! Yes, you can now create new branches directly on this repository. I would recommend creating new branch for each PR.

> Also, if the GIMPS status script could be amended to show the other residue moduli that Mlucas saves, all the better.

OK, I will include this in the next update. That is a great idea to output it with the `-l` flag.

> Finally my understanding is that the Res2048 value is just the lowest 2 kilobits of the residue, _i.e._ equal to _R_ mod 2<sup>2048</sup>

Yes, that is correct. Sorry, that was a typo on my part, I meant a bitwise AND 2<sup>2048</sup>-1, which is the same as a mod 2<sup>2048</sup>, as you said. (When using arbitrary precision integers, as the GIMPS status script does, computing a bitwise AND is much faster than a mod.)

> So I’ve rolled together the various bug-fixes and a couple of small cosmetic changes as discussed into a PR — hopefully I’ve done that okay?

Yes, your PR looks great. Thank you for doing that! I will probably make a few minor cosmetic tweaks as well.
